<a href="https://colab.research.google.com/github/emilaemil/dataset-data-mining/blob/main/dt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#Import library numpy, pandas dan scikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [12]:
#Membaca Dataset dari File ke Pandas dataFrame
dt = pd.read_csv('liver-disorders-dataset.csv')

In [13]:
dt.head()

id  'mcv'  'alkphos'  'sgpt'  'sgot'  'gammagt'  'drinks'  'selector'
0   1     85         92      45      27         31       0.0           1
1   2     85         64      59      32         23       0.0           2
2   3     86         54      33      16         54       0.0           2
3   4     91         78      34      24         36       0.0           2
4   5     87         70      12      28         10       0.0           2

In [14]:
#Menghapus kolom "Id"
dt = dt.drop(labels="id", axis=1)

In [15]:
print(dt)

     'mcv'  'alkphos'  'sgpt'  'sgot'  'gammagt'  'drinks'  'selector'
0       85         92      45      27         31       0.0           1
1       85         64      59      32         23       0.0           2
2       86         54      33      16         54       0.0           2
3       91         78      34      24         36       0.0           2
4       87         70      12      28         10       0.0           2
..     ...        ...     ...     ...        ...       ...         ...
145     90         76      37      19         50       6.0           1
146     96         70      70      26         36       6.0           1
147     95         62      64      42         76       6.0           1
148     92         62      20      23         20       6.0           1
149     91         63      25      26         15       6.0           1

[150 rows x 7 columns]


In [16]:
#Mengubah dataFrame ke array Numpy
dt = dt.to_numpy()

In [17]:
print(dt)

[[85. 92. 45. ... 31.  0.  1.]
 [85. 64. 59. ... 23.  0.  2.]
 [86. 54. 33. ... 54.  0.  2.]
 ...
 [95. 62. 64. ... 76.  6.  1.]
 [92. 62. 20. ... 20.  6.  1.]
 [91. 63. 25. ... 15.  6.  1.]]


In [18]:
#Membagi Dataset => 120 baris data untuk training dan 30 baris data untuk testing
dataTraining = np.concatenate((dt[0:60, :], dt[75:135, :]), 
                              axis=0)
dataTesting = np.concatenate((dt[60:75, :], dt[135:150, :]), 
                             axis=0)

In [55]:
print(dataTraining)
len(dataTraining)

[[ 85.   92.   45.   27.   31.    0.    1. ]
 [ 85.   64.   59.   32.   23.    0.    2. ]
 [ 86.   54.   33.   16.   54.    0.    2. ]
 [ 91.   78.   34.   24.   36.    0.    2. ]
 [ 87.   70.   12.   28.   10.    0.    2. ]
 [ 98.   55.   13.   17.   17.    0.    2. ]
 [ 88.   62.   20.   17.    9.    0.5   1. ]
 [ 88.   67.   21.   11.   11.    0.5   1. ]
 [ 92.   54.   22.   20.    7.    0.5   1. ]
 [ 90.   60.   25.   19.    5.    0.5   1. ]
 [ 89.   52.   13.   24.   15.    0.5   1. ]
 [ 82.   62.   17.   17.   15.    0.5   1. ]
 [ 90.   64.   61.   32.   13.    0.5   1. ]
 [ 86.   77.   25.   19.   18.    0.5   1. ]
 [ 96.   67.   29.   20.   11.    0.5   1. ]
 [ 91.   78.   20.   31.   18.    0.5   1. ]
 [ 89.   67.   23.   16.   10.    0.5   1. ]
 [ 89.   79.   17.   17.   16.    0.5   1. ]
 [ 91.  107.   20.   20.   56.    0.5   1. ]
 [ 94.  116.   11.   33.   11.    0.5   1. ]
 [ 92.   59.   35.   13.   19.    0.5   1. ]
 [ 93.   23.   35.   20.   20.    0.5   1. ]
 [ 90.   6

120

In [65]:
print(dataTesting)
len(dataTesting)

[[ 90.   45.   33.   34.   27.    0.5   2. ]
 [ 90.   72.   14.   15.   18.    0.5   2. ]
 [ 91.   55.    4.    8.   13.    0.5   2. ]
 [ 91.   52.   15.   22.   11.    0.5   2. ]
 [ 87.   71.   32.   19.   27.    1.    1. ]
 [ 89.   77.   26.   20.   19.    1.    1. ]
 [ 89.   67.    5.   17.   14.    1.    2. ]
 [ 85.   51.   26.   24.   23.    1.    2. ]
 [103.   75.   19.   30.   13.    1.    2. ]
 [ 90.   63.   16.   21.   14.    1.    2. ]
 [ 90.   63.   29.   23.   57.    2.    1. ]
 [ 90.   67.   35.   19.   35.    2.    1. ]
 [ 87.   66.   27.   22.    9.    2.    1. ]
 [ 90.   73.   34.   21.   22.    2.    1. ]
 [ 86.   54.   20.   21.   16.    2.    1. ]
 [ 86.   44.   21.   11.   15.    5.    2. ]
 [ 87.   64.   16.   20.   24.    5.    2. ]
 [ 92.   57.   21.   23.   22.    5.    2. ]
 [ 90.   70.   25.   23.  112.    5.    2. ]
 [ 99.   59.   17.   19.   11.    5.    2. ]
 [ 92.   80.   10.   26.   20.    6.    1. ]
 [ 95.   60.   26.   22.   28.    6.    1. ]
 [ 91.   6

30

In [70]:
#Memecah Dataset ke Input dan Label
inputTraining = dataTraining[:, 0:6]
inputTesting = dataTesting[:, 0:6]
labelTraining = dataTraining[:, 6]
labelTesting = dataTesting[:, 6]

In [71]:
#Mendefinisikan Decision Tree Classifier
model = tree.DecisionTreeClassifier()

In [72]:
#Mentraining Model
model = model.fit(inputTraining, labelTraining)

In [73]:
#Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]
Hasil Prediksi :  [2. 2. 1. 2. 1. 1. 2. 2. 2. 2. 2. 1. 2. 1. 2. 1. 2. 2. 1. 2. 1. 2. 1. 2.
 1. 1. 1. 2. 1. 1.]


In [74]:
#Menghitung Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 21 data
Prediksi Salah : 9 data
Akurasi : 70.0 %
